### ISSUE TITLE
尝试运行报错。

### ISSUE THREAD

**Issue by ProjectSky** [AnyISalIn/zhihu_fun#10]
* 系统：ubuntu 16.04
* python版本：3.5.2
* 报错信息
```
sky@Linux:~/github/zhihu_fun$ python3.5 run.py
Process question_parser:
Process url_generator:
Traceback (most recent call last):
  File "run.py", line 29, in question_parser
    qe = QuestionParser(q)
  File "/home/sky/github/zhihu_fun/zhihu_fun/go.py", line 99, in __init__
    self.driver = _get_driver()  # init selenium webdriver
  File "/home/sky/github/zhihu_fun/zhihu_fun/netlib/selenium.py", line 16, in _get_driver
    driver = webdriver.PhantomJS(desired_capabilities=_set_driver_ua())
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service phantomjs unexpectedly exited. Status code was: -6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run.py", line 32, in question_parser
    qe.driver.close()
UnboundLocalError: local variable 'qe' referenced before assignment
Traceback (most recent call last):
  File "run.py", line 11, in url_generator
    g = UrlGenerator(q, keyword_number=config.get('key_number'))
  File "/home/sky/github/zhihu_fun/zhihu_fun/go.py", line 25, in __init__
    self.driver = _get_driver()
  File "/home/sky/github/zhihu_fun/zhihu_fun/netlib/selenium.py", line 16, in _get_driver
    driver = webdriver.PhantomJS(desired_capabilities=_set_driver_ua())
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service phantomjs unexpectedly exited. Status code was: -6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 17, in url_generator
    g.driver.close()
UnboundLocalError: local variable 'g' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run.py", line 20, in url_generator
    Logger.info('Summary: {} Record'.format(len(g.info)))
UnboundLocalError: local variable 'g' referenced before assignment
```
* 另外*.githubusercontent.com是不是挂了，图片都无法显示
* 没想到回复如此之快，误按到了回车，刚填完主题直接发出去了。

**Comment by AnyISalIn** [comment]
请提供错误信息

**Comment by AnyISalIn** [comment]
你 phantomjs 是哪个版本的，别用 apt-get 直接装，可能版本较低

**Comment by AnyISalIn** [comment]
图片是我的问题，太大了，压缩了还是挺大的。。。

**Comment by ProjectSky** [comment]
* phantomjs 版本
```
dpkg -l | grep phantomjs
phantomjs  2.1.1+dfsg-1
```
* 头像都挂了，提示无法解析*.githubusercontent.com的DNS地址。

**Comment by AnyISalIn** [comment]
你可以试试卸载了然后用 README 的方式安装看看，https://github.com/AnyISalIn/zhihu_fun#安装-phantomjs

**Comment by ProjectSky** [comment]
已解决，十分感谢。
