### ISSUE TITLE
readme 对小白如我不太友好

### ISSUE THREAD

**Issue by iiiyu** [AnyISalIn/zhihu_fun#5]
一个爬虫为啥还要配置 Nginx 啊
```
$ vim go.html # 修改 <base href="http://localhost:8000"> 的地址为你当前的地址
```
这个又是什么意思啊 

我run 了以后 报错
```
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from zhihu_fun.go import UrlGenerator, QuestionParser, basedir
  File "/Users/iYu/Developer/Github/zhihu_fun/zhihu_fun/go.py", line 141
SyntaxError: Non-ASCII character '\xe8' in file /Users/iYu/Developer/Github/zhihu_fun/zhihu_fun/go.py on line 141, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by AnyISalIn** [comment]
配置 Nginx 是为了，预览爬下来的图片，本来想直接用 Python 的 http.server 来跑的，但是感觉不是很好，也不一定需要 Nginx，其他的也行。

修改 go.html 这个是指定 http server 的起始路径

运行报错这个看起来像是 Python 2 运行的问题，请用 Python 3

**Comment by AnyISalIn** [comment]
Nginx 不配置也可以，爬虫运行的时候，会生成一个 image_meta.json 的文件，里面有每张图片的元数据信息，可以自行通过这个 json 文件做前端展示。。

**Comment by AnyISalIn** [comment]
前端展示这块，因为我不会 JS，只是从网上抄了点代码，所以不是很科学

**Comment by iiiyu** [comment]
...囧 看来 我是不是应该好好学习一下了 Python 才能 run 起来吧
Python2 这个是我的锅。。。忘记按3了。 
方便留个 IM 的联系方式么？ 目前感觉这个东西很好玩的样子 想run 起来看看。。。

**Comment by iiiyu** [comment]
```
╰─± python3 run.py
2017-04-02 19:35:46,137 INFO [url_generator] [MainThread] - Initialize PhantomJS Webdriver
2017-04-02 19:35:46,137 INFO [question_parser] [MainThread] - Initialize PhantomJS Webdriver
Process question_parser:
Traceback (most recent call last):
  File "run.py", line 29, in question_parser
    qe = QuestionParser(q)
  File "/Users/iYu/Developer/Github/zhihu_fun/zhihu_fun/go.py", line 102, in __init__
    self.driver = _get_driver()  # init selenium webdriver
  File "/Users/iYu/Developer/Github/zhihu_fun/zhihu_fun/netlib/selenium.py", line 18, in _get_driver
    _set_cookies(driver, my_session().cookies)
  File "/Users/iYu/Developer/Github/zhihu_fun/zhihu_fun/netlib/selenium.py", line 33, in _set_cookies
    driver.add_cookie({'name': c.name, 'value': c.value, 'path': c.path, 'expiry': c.expires, 'domain': c.domain})
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 673, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: {"errorMessage":"Can only set Cookies for the current domain","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"183","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:57014","User-Agent":"Python-urllib/3.6"},"httpVersion":"1.1","method":"POST","post":"{\"cookie\": {\"name\": \"_xsrf\", \"value\": \"78c969f7c33617a851e1044a3c350f6f\", \"path\": \"/\", \"expiry\": null, \"domain\": \"www.zhihu.com\"}, \"sessionId\": \"832cd230-1798-11e7-97ee-5198f716449a\"}","url":"/cookie","urlParsed":{"anchor":"","query":"","file":"cookie","directory":"/","path":"/cookie","relative":"/cookie","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/cookie","queryKey":{},"chunks":["cookie"]},"urlOriginal":"/session/832cd230-1798-11e7-97ee-5198f716449a/cookie"}}
Screenshot: available via screen


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run.py", line 32, in question_parser
    qe.driver.close()
UnboundLocalError: local variable 'qe' referenced before assignment
Process url_generator:
Traceback (most recent call last):
  File "run.py", line 11, in url_generator
    g = UrlGenerator(q, keyword_number=config.get('key_number'))
  File "/Users/iYu/Developer/Github/zhihu_fun/zhihu_fun/go.py", line 27, in __init__
    self.driver = _get_driver()
  File "/Users/iYu/Developer/Github/zhihu_fun/zhihu_fun/netlib/selenium.py", line 18, in _get_driver
    _set_cookies(driver, my_session().cookies)
  File "/Users/iYu/Developer/Github/zhihu_fun/zhihu_fun/netlib/selenium.py", line 33, in _set_cookies
    driver.add_cookie({'name': c.name, 'value': c.value, 'path': c.path, 'expiry': c.expires, 'domain': c.domain})
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 673, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: {"errorMessage":"Can only set Cookies for the current domain","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"183","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:57015","User-Agent":"Python-urllib/3.6"},"httpVersion":"1.1","method":"POST","post":"{\"cookie\": {\"name\": \"_xsrf\", \"value\": \"36d1f774be043eb450f459b8b73d7725\", \"path\": \"/\", \"expiry\": null, \"domain\": \"www.zhihu.com\"}, \"sessionId\": \"832cd230-1798-11e7-9d9c-5f247bc37bda\"}","url":"/cookie","urlParsed":{"anchor":"","query":"","file":"cookie","directory":"/","path":"/cookie","relative":"/cookie","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/cookie","queryKey":{},"chunks":["cookie"]},"urlOriginal":"/session/832cd230-1798-11e7-9d9c-5f247bc37bda/cookie"}}
Screenshot: available via screen


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 17, in url_generator
    g.driver.close()
UnboundLocalError: local variable 'g' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "run.py", line 20, in url_generator
    Logger.info('Summary: {} Record'.format(len(g.info)))
UnboundLocalError: local variable 'g' referenced before assignment
```

**Comment by AnyISalIn** [comment]
qq: 1449472454, 其实还是我写的不够好。。。

**Comment by xyrobo** [comment]
![image](https://cloud.githubusercontent.com/assets/13051065/24692775/2ea50ecc-1a0d-11e7-9627-1096cb621d26.png)
你的报错解决了，没觉得试着添加这个？

**Comment by AnyISalIn** [comment]
其实只要在 PATH 下就没问题的。。
